SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS teachers;
DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS teachings;
DROP TABLE IF EXISTS notifications;
DROP TABLE IF EXISTS notifications_recipients;
SET FOREIGN_KEY_CHECKS = 1;